### ISSUE TITLE
Landing/home page

### ISSUE THREAD

**Issue by thomasmetta** [Developer-DAO/developerdao.com#114]
Right now if a user lands on the home page, they probably will be very confused what the site is for and why there's a search function. I propose that we have a simple landing page and move our current page to a Search tab

This is kinda related to https://github.com/Developer-DAO/developer-dao/issues/110. Given we are still trying to figure out what the purpose of the DAO, we can have twitter snippet of what the community is saying about developerdao. I have seen great tweet regarding developerdao and we should definitely showcase those and add a CTA for joining the discord. Since the discord is token gated, we need to showcase what the member is expecting after they join.

What to show on home page
- Short mission statement
- Twitter snippet
- Discord CTA
- Number of Tokens left /8000
- Number of people in the discord

**Comment by codingwithmanny** [comment]
I like this approach.

Re: Twitter snippet

Snippets from official Developer Dao twitter or snippets from devs in the community?

**Comment by thomasmetta** [comment]
I would say not from official developerdao twitter since it's more convincing if it's from community members

Example snippet:

https://twitter.com/dhaiwat10/status/1437930758270709761
https://twitter.com/codingwithmanny/status/1438508253692903424
https://twitter.com/NHeinDev/status/1437101365701058562
https://twitter.com/aabugosh/status/1439665949934825476


Yes, design always first 😄

**Comment by marbiano** [comment]
Would you folks accept a hand on the design part? I would gladly like to ontribute with the first iteration at what you so clearly described above.

**Comment by codingwithmanny** [comment]
Yeah happy to make this a team effort @marbiano.
Did you want to start the base figma file for a wireframe to start with, with some placeholder text, etc?

**Comment by marbiano** [comment]
Yup, I was planning to start from the base Figma file. Will keep you posted!

**Comment by Dhaiwat10** [comment]
I'll volunteer to write the code for this once the design is ready. :)

**Comment by marbiano** [comment]
Alright, showtime!

**Light mode:**
<img width="1440" alt="d_d-light" src="https://user-images.githubusercontent.com/5664/134742141-b1d0bcce-65a5-421f-a579-b8985c871fb3.png">

**Dark mode:**
![d_d-dark](https://user-images.githubusercontent.com/5664/134742148-63f3c378-25e0-43b1-961d-25205937e362.png)


Some extra comments:
- Text is probably wrong, just wanted to put something out there.
- I introduced a new typeface and the purple color. Those are just proposals. The Figma file where I got the landing includes a quick style guide with details about those two. [Here's the file](https://www.figma.com/file/NuGyq4CdJaCFAt6oubMcVv/D_D?node-id=0%3A1) I'm working in case you are curious.
- The tweets section was a great idea @thomasmetta, I love how dynamic it makes the page look. For mockup purposes, I stole it from both Netlify and Stitches homepages, I plan to work on our own custom boxes at a more advanced stage of the process.

Thoughts?

**Comment by Dhaiwat10** [comment]
Looks great! 😍 Just one question before I start converting this into code though:

The Figma file you mentioned is just a style guide, I suppose? Can you share the Figma file for the actual landing page design too? Thanks!

**Comment by marbiano** [comment]
@Dhaiwat10 the linked Figma file has multiple pages, where you can get the primitives for typefaces, colors, grid, and a fourth one which is where I started working on the landing page.

If you can hold until next week, that would give me enough time to polish the design and work on the responsiveness of it. 

Also, I'd love to set a call so we can discuss and agree on some things regarding the implementation. I plan to participate on coding this too, so I feel like the most we can agree upfront, the better would be for having an organic teamwork process.

Thougts?

**Comment by kempsterrrr** [comment]
@marbiano this is looking good! Going to brain dump some thoughts below:

- Our name "Developer DAO" is not currently on the page, think it would be goo to add this somewhere. Maybe either next to the logo in the top-left or above the current main headline "Developers into Web3".
- Do we want some kind of instructions onsite about how to join? Sending new comers to open sea could be quite confusing for them if they've never minted an NFT before. Maybe the `Become a member` button to auto-scroll down the page to a `How do I join` guide (happy to draft this or just copy content from the repo/s `readme`).
- Could also add some more about benefits of joining the DAO (maybe below the fold but before the 'How too' to help converting visitors to members). Picturing a simple grid like [this](https://tailwindui.com/components/marketing/sections/feature-sections#component-64ac58e032276db96bf343a8d4f332a8) or [this](https://tailwindui.com/components/marketing/sections/feature-sections#component-cdca7eda27bdaceb45026dca4c17efe7) design from Tailwind UI.

Some thoughts about what those benefits could be:

1. `Private Discord Access` - engage directly with (800+) active members that includes Web3 founders, team members from Ethereum/Polygon foundations, major open source project maintainers and many other passionate/talented folk.
2. `Ownership & voting rights` - own what you help to build via our upcoming $DBUCKS token launch with fair allocation based on each persons contributions to the community.
3. `Learning & support` - active discussion and support channels for Solidity, Solana, Polkadot, dApps plus Web3 learning resources organised by the community.
4. `Events` - Join in with community events either just to learn and connect or help build your personal brand.

Are we also going to update the design for `/projects` or do we potentially just role them into this page?

Totally up for contributing anyway I can with this. Although we don't have our mission statement down I think we can showcase some really compelling reasons to join, even if some are aspirational! My last role was Head of Growth so I've spent a lot of time with my head in the space of attracting, informing and converting people (although I can't actually create a finished design 😂 )

Happy to jump on a brainstorm session anytime :)

@Dhaiwat10 you can find the figma landing page design [here](https://www.figma.com/file/NuGyq4CdJaCFAt6oubMcVv/D_D?node-id=7%3A2).

**Comment by with-heart** [comment]
@marbiano The designs are gorgeous! Thanks for taking the time to put something together and get the ball rolling with this. It'll be a nice facelift for the site and will greatly improve DevDAO marketability.

@allcontributors please add @marbiano for design

**Comment by kempsterrrr** [comment]
There have been some super interesting comments in discord that would be awesome to showcase as well, just leaving here as a record so I don't have to find them again 😂 

[First examples from @sdfsdf](https://discord.com/channels/883478451850473483/883705562850807808/890223340697055252)
> Just a short note to say the D DAO continues to bring real life connections. The network of devs here is strong 💪 . Thx all.

[another example from @mfnkl](https://discord.com/channels/883478451850473483/884171317753040976/884537431913803786)
> If anyone’s wondering how this went, we hopped on a call and are working together on a mvp. What a great community!

Don't know if we could mix them in with the twitter cards?

**Comment by with-heart** [comment]
> Could also add some more about benefits of joining the DAO

I think that's essential for us. We have some star power that would enable us to grab people's attention enough to visit the site, and that's where we can really seal the deal and convince them to join.

---

Regarding the design & implementation, I want to think out loud about a few things with yall (all regarding Chakra UI):

- Chakra comes with its own design system. It's easy to modify through its theming system, so I think it'd be valuable for us to map out what changes we'd need to make to the Chakra design system.
- Chakra has [an official figma kit](https://www.figma.com/community/file/971408767069651759). I think it'd be solid to for us to build our figma design system on top of the kit to keep things consistent between design and implementation. 
- Integrating as many of the proposed design system changes with the Chakra `theme` in our codebase would go a long way in establishing consistency between our components and make things easier to maintain long-term. This plays well with the first point, as it'd make it very easy to accomplish this.

Just some things that jumped out at me as I was reading through this thread. Thoughts?

**Comment by Dhaiwat10** [comment]
@marbiano 
- My bad for not spotting that! I don't use Figma too often haha.
- Sure, please take your time in polishing the design.
- I would be down for a call. I agree with you on the 'being on the same page' point. 😄

@kempsterrrr Those are some excellent points. Thanks for writing that up! I think a brainstorming session along with anyone else who wants to join would be a great idea.

@with-heart agree with you on the Chakra UI points. We should 100% leverage it 👍🏻

**Comment by thomasmetta** [comment]
> There have been some super interesting comments in discord that would be awesome to showcase as well, just leaving here as a record so I don't have to find them again 😂
> 
> [First examples from @sdfsdf](https://discord.com/channels/883478451850473483/883705562850807808/890223340697055252)
> 
> > Just a short note to say the D DAO continues to bring real life connections. The network of devs here is strong 💪 . Thx all.
> 
> [another example from @mfnkl](https://discord.com/channels/883478451850473483/884171317753040976/884537431913803786)
> 
> > If anyone’s wondering how this went, we hopped on a call and are working together on a mvp. What a great community!
> 
> Don't know if we could mix them in with the twitter cards?

These are great. Maybe we can screenshot those and add those in the about page as well so the landing page wont get too bloated? The twitter snippet for Home page and Discord screenshot for About page for people to find out more without joining the channel

**Comment by thomasmetta** [comment]
We have a lot of good pointers here. We can always ship something simple first and iterate on it since it's gonna better than what we currently have.

**Comment by marbiano** [comment]
You have all brought excellent points, that's exactly what I was looking for!

I'm typically a bit slower during the weekend but I'll try to bring most of your feedback into the design as soon as I can.

I'm specially interested into making the updates that would enable the project to keep using Chakra easily. I should have started from there, but since I typically build this from scratch, missed that one. Sorry for that, will try to merge the design with Chakra's kit.

Happy to jump into a quick call on Monday so we can all stay on the same page.

**Comment by marbiano** [comment]
Alright folks, here's the new WIP Figma file: https://www.figma.com/file/1QjhvUGytv6cLjZiAPLYLz/D_D-Figma-Kit?node-id=0%3A1

I basically duplicated Chakra's one and started modifying where it needed to be.

Also copied the landing page design to that file but still haven't changed it, will update this issue once that's done so we can jump on a call and discuss!

**Comment by marbiano** [comment]
Here's the updated version of the design (light mode only):

<img width="1440" alt="d_d-light-02" src="https://user-images.githubusercontent.com/5664/134996523-d5346b60-544c-4a81-9a70-1c7371849692.png">

Comments:

1. Most of the page has been updated to use standard Chakra theme tokens, as per @with-heart's suggestion.
2. We are going to need to customize our Chakra's theme. Happy to help with instructions and/or code when we get to that part.
3. There are two Figma custom components that I'm proposing to add to the system, `Tweet` and `Super Button`. The latter is a slightly more interesting version of the standard Chakra button. Once we get to implementation I might add states for hover/active on both of them, it's just easier and most natural to me to do that in the browser directly.
4. Using the new Tweet component, we now have our own wall of tweets, no more screenshots from Netlify's homepage!
5. Added a benefits section per @kempsterrrr's suggestion. Will (and whoever is also interested), feel free to play with the text page-wide as much as you want, it's really not my strongest skill.
6. Icons on the benefits section are not final, just quickly used what Chrakra's UI Kit provides out of the box.
7. Didn't add instructions for minting because I saw that we are close to having a page for direct minting, so all those calls to action could just become a link to that page.
8. Once the light version is locked, I'll update the dark one too.

Alright, let me know what you think. Also, can we plan to have a proper call once the design is done and we are ready to kickstart the implementation phase?

**Comment by narbs91** [comment]
I share the same sentiment as the rest of the gang @marbiano , the design looks dope!  One question i have is around the intent of the "become a member" and "Mint now and join the DAO" buttons, are they meant to do the same thing (i.e mint a token)?  Are both buttons meant to land on a new page with the changes coming in the Direct minting PR(I assume they are)?  

The point i want to get across is perhaps we can stick with a consistent labelling with all the pathways to get someone to join since "Become a member" implies one intent (i.e I could be minting or I could be joining the discord) but "Mint now and join the DAO" could mean two things (i.e mint and join the discord).  It's mostly nitpicking on my part on this but from experience users sometimes misunderstand what a particular button may represent if the wording doesn't quite match.  Without really having any metrics/analytics atm it would be hard to tell anyhow; however, thinking about this more as i write this comment perhaps we can add a little section somewhere to explain that you need to mint the NFT so that you can join the Discord/be a member.

**Comment by Dhaiwat10** [comment]
@marbiano The design looks amazing. Thanks for all the work! :D 

Agreed about the call. Let us know when the design is ready & we will plan out the call!

**Comment by gjsyme** [comment]
> Once the light version is locked, I'll update the dark one too.

You may already be planning this, but Chakra has the [Color Mode](https://chakra-ui.com/docs/features/color-mode) that lets you swap over to dark mode and all its elements *should* (assuming we're only using their components and things work as advertised) switch over. It may be worth setting light mode, implementing, and then seeing if there's any work needed to make Dark mode better/different than we get from Chakra.

**Comment by marbiano** [comment]
> Are both buttons meant to land on a new page with the changes coming in the Direct minting PR(I assume they are)?

Yup, that was the plan.

> The point i want to get across is perhaps we can stick with a consistent labelling with all the pathways to get someone to join since "Become a member" implies one intent (i.e I could be minting or I could be joining the discord) but "Mint now and join the DAO" could mean two things (i.e mint and join the discord). 

Yeah, I fully agree. Text and wording are not precisely my strong suit.

> Agreed about the call. Let us know when the design is ready & we will plan out the call!

Was planning to use today's call to talk a bit about the next steps. Hopefully you can join!

> You may already be planning this, but Chakra has the [Color Mode](https://chakra-ui.com/docs/features/color-mode) that lets you swap over to dark mode and all its elements _should_ (assuming we're only using their components and things work as advertised) switch over. It may be worth setting light mode, implementing, and then seeing if there's any work needed to make Dark mode better/different than we get from Chakra.

Good to know, I haven't really used Chakra before so learning new things every day. I'm already proposing to customize some tokens on the default design system, so I'm not sure how those will reflect. I'll throw a quick dark mode just to have as a reference for when doing the implementation.

**Comment by with-heart** [comment]
@marbiano I was hoping you'd want to talk about that today so that's perfect!

**Comment by Dhaiwat10** [comment]
Hey everyone, I couldn't attend the call (was 1am for me :( ). Did you discuss the landing page during the call? I couldn't find anything about the landing page in the meeting notes apart from a link to this issue. 

I'd really appreciate a brief of what you discussed & what we're planning! :D

**Comment by gjsyme** [comment]
Shortest answer is that ideally things can run in parallel; I believe that would mean you'd be able to get started trying to match to the light mode drawing with the understanding that there will be word changes and maybe some final changes to the page as @marbiano finalizes the look.
There is also a video recording linked from the call notes (we spent a good chunk of time on design/the landing page topic).

**Comment by marbiano** [comment]
Yeah, there's a couple of things that are related to you @Dhaiwat10, so you might want to take a look at the recording.

**Comment by Dhaiwat10** [comment]
Thanks! I'll def have a look at the recording. I somehow missed it while going through the notes.

**Comment by Dhaiwat10** [comment]
Alright, I'm gonna get the ball rolling on my fork & put in a draft PR once I have something.

**Comment by G3root** [comment]
Is this open for pr other than team members ?

**Comment by with-heart** [comment]
@G3root Absolutely! There is an open draft PR from @Nazeeh21 with a partial implementation so maybe there's a way yall could collaborate to bring one of these over the finish line? You're also welcome to open a draft PR so we can see what you have completed so far too.

**Comment by narbs91** [comment]
@with-heart @codingwithmanny do we still want to keep this open?

**Comment by codingwithmanny** [comment]
@narbs91 I'd close it for archiving purposes.

**Comment by narbs91** [comment]
As we are shifting the purpose of the website pending a decision from the design guild we are putting a pause on all non maintenance/house keeping issues. As such i'll be closing this issue. Thanks for the interest in the website but tune back a little later when the new direction has been established
