### ISSUE TITLE
Missing Translation(s)

### ISSUE THREAD

**Issue by TrevorFrench** [Developer-DAO/developerdao.com#118]
### PR #

104

### Translation Keys

Nesting needs to be added on "ZH" files

### List of missing locales

zh-CN, zh-HK, zh-TW, zh

**Comment by TrevorFrench** [comment]
In reference to issue #91

**Comment by kavimaluskam** [comment]
I can help to update the `zh` files.

**Comment by narbs91** [comment]
Marking issue as completed
