### ISSUE TITLE
[Bug]:  Discourse does not appear in footer

### ISSUE THREAD

**Issue by bee-san** [Developer-DAO/developerdao.com#139]
### What happened?

![image](https://user-images.githubusercontent.com/10378052/136827039-280bcef3-98c1-4930-9ec0-ad16c8f321d2.png)

https://forum.developerdao.com/

### How to reproduce the bug?

Visit https://www.developerdao.com/projects for example

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### What device type(s) did you see the problem on?

- [ ] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating system(s) did you see the problem on?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Dhaiwat10** [comment]
Yep. You'll have to create a pull request. Did you create a fork?
