### ISSUE TITLE
Add e2e tests for direct mint

### ISSUE THREAD

**Issue by narbs91** [Developer-DAO/developerdao.com#154]
### Context / Background / How This Idea Came To Fruition

While working on adding testing for #147 efforts were thwarted when hitting a roadblock around how to mock a wallet.  This enhancement looks to add e2e testing for direct minting.

### Problem / Opportunity

Mocking a wallet for a test (unit or e2e) seems non trivial after much research by @Ibby-devv and thus a great opportunity for D_D members to come together to solve.

### Proposed Solution / How It Can Be Improved

The current options at hand involve looking at an existing/established dApp to mimic/learn or turning to an Alpha version of a wallet mocking library. 

Examples of established dApps to study:
- https://github.com/EthWorks/useDApp/tree/master/packages/testing
- https://github.com/ensdomains/ens-app

Alpha version of testing library:
- https://github.com/VGLoic/eth-testing

On Oct 29th @codingwithmanny initiated and led a group exploratory/coding huddle around playing around with ideas to mock connecting to a wallet.  A skeleton repo was created that we can use to play around with ideas before leaning in on an implementation: 

https://github.com/codingwithmanny/wallet-tests

So there is no "proposed solution" wrt to the "how" but the e2e tests should cover the following cases:

 - Expected Negative Interactions
 - User unsuccessfully connects wallet 
 - Insufficient funds for mint
 - Transaction failed (could not connect)
 - Token already minted
 - Expected Positive Interactions
 - User Connects Wallet Successfully
 - User successfully starts transaction to mint token
 - User successfully mints token

(kudos to @codingwithmanny and @Ibby-devv for drawing up the test cases)

### Testing the changes

Expectation is that existing e2e will continue to run successfully ontop of the test cases we're looking to add as part of the issue

### Additional Information

If we hit a roadblock, it might be worthwhile to reach out to some of the more prominent dApp repos too see if they can spend some time going over how they solved the problem of mocking a wallet

**Comment by narbs91** [comment]
So i was messing around a bit with the original code base that @codingwithmanny spun up but was unable to successfully mock the window object with ethereum.  I then went down the rabbit hole of trying to mock up a wallet provider to be able to use for e2e tests:  

```javascript
import { walletProps } from './wallet-interface';


// Inspired by https://github.com/rsksmart/mock-web3-provider
const mockProvider = (props: walletProps) => {
    const { chainId, privateKey, address, provider } = props;

    const getMethod = (_method: string) => {
        switch (_method) {
            case 'eth_requestAccounts': return address
            default: return Promise.reject(`The method ${_method} is not implemented by the mock provider.`)
        }

    }

    const builder = {
        isMetaMask: provider === 'metamask' ? true : false,
        chainId: chainId,
        selectedAddress: address,
        networkVersion: chainId,

        request(props: { method: string, params: string[] }) {
            return getMethod(props.method);
        }
    }

    return builder;
}

export default mockProvider;
```

```javascript
export type walletProps = {
    chainId: string,
    privateKey: string,
    address: string,
    provider: string
}
```

Test ex:  

```javascript
const testProps = {
    chainId: "4",
    privateKey: "1234",
    address: "0x000000000000000000000000",
    provider: "metamask",
  } as walletProps;

  const walletProvider = mockProvider(testProps);
  const accounts = await walletProvider.request({
    method: "eth_requestAccounts",
    params: [],
  });
  expect(accounts).toBe(testProps.address);
```

(Note pasting code here because i couldn't push my branch to Manny's repo)

This was Inspired by this [library](https://github.com/rsksmart/mock-web3-provider) I found while googling.  We could either look to utilize this for the time being or look to build something similar ourselves that a bit more flexible (this one only seems to cater to metamask).  

Let me know what you all think @codingwithmanny @with-heart @gjsyme @Dhaiwat10 @Ibby-devv

**Comment by Dhaiwat10** [comment]
@narbs91 that's some real progress. Nice work! Is there any library that mocks other wallets like WalletConnect?

**Comment by narbs91** [comment]
Not that i've found yet but it seems the choices out there are pretty few and far between.  Will have to do a bit more research but this kinda comes back to a side conversation @Ibby-devv around we potentially trying to build a library around mocking a wallet/blockchain interaction

**Comment by Ibby-devv** [comment]
I honestly think we should try and build our own library. We can start small and build on it. We can break it up into small chunks and let people work on a small aspect of the whole project and then bring it all together. It is definitely needed in the space from my brief research thus far.

**Comment by Dhaiwat10** [comment]
>  a side conversation @Ibby-devv and i had around potentially trying to build a library around mocking a wallet/blockchain interaction as a D_D project

That's what I was getting onto as well! Let's do it

**Comment by narbs91** [comment]
Dope, we should def spin up a proposal for what we're looking to do so we can make it an official dao project; however, that would mean this issue would stay in limbo until we can that MVP version out.  If we go the route of building the library we def would want to show it off in use as something we use in our codebase.

**Comment by narbs91** [comment]
Sorry forgot to CC you too @kavimaluskam I know you were interested in the e2e too, would love your input too

**Comment by Ibby-devv** [comment]
> building

We could concentrate v1.0 to deal primarily with the test cases required for our minting process. Most of the functions are straightforward such as insufficient funds, wallet address and a transaction.

**Comment by Ibby-devv** [comment]
> Dope, we should def spin up a proposal for what we're looking to do so we can make it an official dao project; however, that would mean this issue would stay in limbo until we can that MVP version out.  If we go the route of building the library we def would want to show it off in use as something we use in our codebase. 

We could concentrate v1.0 to deal primarily with the test cases required for our minting process. Most of the functions are straightforward such as insufficient funds, wallet address and a transaction.

**Comment by narbs91** [comment]
Yep, we def should concentrate on a mvp and then iterate on that

**Comment by codingwithmanny** [comment]
Still working on this, but I'll try and give an update on it at the website meeting.

**Comment by with-heart** [comment]
> Still working on this, but I'll try and give an update on it at the website meeting.

DRAFT PR!???

**Comment by narbs91** [comment]
@codingwithmanny 's been dabbling in the general direction of a solution in his [own spun up repo](https://github.com/codingwithmanny/web3-react-jest-tests) which he started when we did a mini code together last week.   It's looking like we might end up using it as a base/guide i would suspect given how much effort he's put into it

**Comment by codingwithmanny** [comment]
> > Still working on this, but I'll try and give an update on it at the website meeting.
> 
> DRAFT PR!???

😂 I'm working on it. @narbs91 it's right about the dabbling part. I needed to figure out the idea first before bringing it into the repository. I'm still on the unit tests part and then my next step is the E2E part.

**Comment by narbs91** [comment]
As we are shifting the purpose of the website pending a decision from the design guild we are putting a pause on all non maintenance/house keeping issues.  As such i'll be closing this issue.  Thanks for the interest in the website but tune back a little later when the new direction has been established
