### ISSUE TITLE
Making the navigation bar responsive

### ISSUE THREAD

**Issue by narbs91** [Developer-DAO/developerdao.com#156]
### Context / Background / How This Idea Came To Fruition

After adding the direct minting feature it was noted that the navigation bar is not mobile friendly and requires the user to side scroll (🤮 ) to see the minting and project links:

![image](https://user-images.githubusercontent.com/29411347/139520604-351b222b-d79d-414f-a967-22b0ba38d6fd.png)

### Problem / Opportunity

As a cutting edge web3 dApp we should aim to be mobile first and make our site as responsive as possible.

### Proposed Solution / How It Can Be Improved

The proposed solution is to make the current navigation bar turn into a "hamburger" menu once crossing the mobile break point.  The following are screenshots of the [chakra-ui page](https://chakra-ui.com/docs/getting-started) depicting the desired ui treatment: 

**Closed**

![image](https://user-images.githubusercontent.com/29411347/139520685-b9912c5e-0d5f-49a2-a5cc-df3754d641ef.png)

**Open**

![image](https://user-images.githubusercontent.com/29411347/139520703-b81f5244-db3c-4742-9aa2-20e493ff4196.png)

The design can be put up for discussion and mocks provided by designers but the above is the most standard approach taken by websites

### Testing the changes

Testing will come down to a combination of unit tests being written for the new elements of the page, e2e test for interacting with the navigation in mobile and manual testing (i.e. navigation functionality does not break and works as intended)

**Comment by narbs91** [comment]
@theprojectcode Has said he would like to take this on

**Comment by theprojectcode** [comment]
Yes. Please assign this to me @narbs91

**Comment by theprojectcode** [comment]
<img width="574" alt="Screen Shot 2021-10-30 at 9 02 00 PM" src="https://user-images.githubusercontent.com/88997637/139563685-56a9d30d-96a1-4dd1-aa45-c2567fd0c470.png">

**Comment by theprojectcode** [comment]
Any reason I'm getting the above error when I attempt to download the yarn package manager? I have npm already installed. Is it fine if I run that as my package manager @narbs91

**Comment by narbs91** [comment]
Hmm did you happen to install npm and node via sudo?  Looks like the folders it's complaining about have restricted perms.  If that's the case you can look to grant read/write access to the folders it complaining about and then try again

**Comment by narbs91** [comment]
Another thing to consider is perhaps switching to nvm to manage the node versions so that you can bypass the perm issue

**Comment by theprojectcode** [comment]
I figured it out. I ran brew install and it added the dependencies. Thanks.

**Comment by theprojectcode** [comment]
@narbs91

**Comment by theprojectcode** [comment]
<img width="475" alt="Screen Shot 2021-10-31 at 11 54 27 PM" src="https://user-images.githubusercontent.com/88997637/139623625-4feb6758-cf97-46e3-a626-3c802f23ab47.png">

**Comment by theprojectcode** [comment]
Should I be concerned? The error that I'm seeing says this - "Cannot find module 'react-i18next' or its corresponding type declarations." any suggestions?

**Comment by theprojectcode** [comment]
I fixed it. I just needed to run yarn install.🤦🏾‍♂️

**Comment by with-heart** [comment]
Sometimes you just have to think out loud! 💜 Glad you're making some progress!

**Comment by theprojectcode** [comment]
Chakra's docs don't have as good of information about responsive navbars as I hoped. Would it be possible to use React docs or tutorials for this?

**Comment by narbs91** [comment]
You most certainly go that route with the react docs but perhaps @with-heart may know some under the hood magic in Charka for us get a responsive nav bar

**Comment by with-heart** [comment]
There's a derivate project of Chakra UI called Choc UI that showcases examples of custom components built using Chakra. They have a [Navbars page](https://choc-ui.tech/docs/navigation/navbars) that might be helpful to you. If you click the "Show Editable Component Code" button on each example, it'll show you the source.

**Comment by theprojectcode** [comment]
Ok nice! I'll check that out! @with-heart Thanks!

**Comment by dizthewize** [comment]
@theprojectcode how far along are you with this? Feel free to let me know if you need any assistance

**Comment by narbs91** [comment]
This feature is complete, closing the issue
