### ISSUE TITLE
Missing Translation(s) - pt-BR

### ISSUE THREAD

**Issue by gjsyme** [Developer-DAO/developerdao.com#164]
### PR #

94

### Translation Keys

projects

### List of missing locales

pt-BR

**Comment by narbs91** [comment]
As we are shifting the purpose of the website pending a decision from the design guild we are putting a pause on all non maintenance/house keeping issues. As such i'll be closing this issue. Thanks for the interest in the website but tune back a little later when the new direction has been established.

Many of the keys will be removed, so no more need for translation here
