### ISSUE TITLE
[Feature]: Link to Developer DAO Substack

### ISSUE THREAD

**Issue by gjsyme** [Developer-DAO/developerdao.com#171]
### Context / Background / How This Idea Came To Fruition

https://developerdao.substack.com/ is a thing. We should point people to it from our webpage.

### Problem / Opportunity

Problem: There is a substack that we run that people are unaware of.
Opportunity: Make the entire world (that visits our website) aware of our substack

### Proposed Solution / How It Can Be Improved

A link (maybe even a form, if such a plugin exists) to the substack / sign up for hte substack https://developerdao.substack.com/

### Testing the changes

Users will at least be able to navigate to the substack.
If supported, users will be able to sign up for the substack directly.

### Additional Information

Substack: https://developerdao.substack.com/

**Comment by embiem** [comment]
There's a way to embed the substack sign-up: https://support.substack.com/hc/en-us/articles/360041759232-Can-I-embed-a-signup-form-for-my-publication-

Can someone who has access to the substack account paste the iframe code here?

Also, would we want to add the signup on the new landing page, or rather as an extra page? 
I personally would add the embedded sign-up in the Landing Page and additionally add a link to our substack to the socials in the footer.

**Comment by gjsyme** [comment]
I think it makes sense to do on the landing page - which probably means that this will have to be integrated with #114. I see you requested the link on discord - thanks for that!

**Comment by kempsterrrr** [comment]
Thanks @embiem for the nudge in discord, embed for substack email signup form below

`<iframe src="https://developerdao.substack.com/embed" width="480" height="320" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>`

Ping back in discord if you need anything else :)

**Comment by narbs91** [comment]
As we are shifting the purpose of the website pending a decision from the design guild we are putting a pause on all non maintenance/house keeping issues.  As such i'll be closing this issue.  Thanks for the interest in the website but tune back a little later when the new direction has been established
