### ISSUE TITLE
[Feature]: Storybook for UI Component testing

### ISSUE THREAD

**Issue by alanpcurrie** [Developer-DAO/developerdao.com#173]
### Context / Background / How This Idea Came To Fruition

Thinking about the future UI maintainability and testability. Storybook is a potential solution for documentation components and implementing accessibility testing  

Storybooks visual regression tool Chromatic can be used along with the unit and e2e tests to maintain quality. 

### Problem / Opportunity

As the system grows, a source of truth documenting component styles and use will be useful for visual consistency code style, accessibility, and re-use. 

Storybook can be used in conjunction with Figma to maintain a brand style guide and create a collaborative experience between Designers and Developers on the team, creating a shared design language 

It will help to keep the site maintainable as we scale 

### Proposed Solution / How It Can Be Improved

integrate Storybook and it's associated plugins into the exisiting testing strategy

- include plugin for A11y testing
- Incude config for Chakra compatability 
- include config for Next router compatability
- include config for react-i18next compatability
- include an example component/story: Nav
- Publish storybook to Chromatic

![Developer-DAO-Nav-Navigation-Links-⋅-Storybook(1)](https://user-images.githubusercontent.com/3331005/140758846-01be6900-7455-4ea2-9332-1fbdfa4d4b8d.png)

### Testing the changes

As a developer DAO website contributor, I expect to be able to view React components on a dedicated Storybook Chromatic URL, so that I can view component documentation, styles, A11y test output, and regression test  output. 

Local testing can be carried out on **http://localhost:6006/** by running **yarn storybook**

### Additional Information

**Useful storybook links:**

https://storybook.js.org/
https://storybook.js.org/addons/@storybook/addon-a11y
https://storybook.js.org/addons/storybook-figma
https://www.chromatic.com/
https://www.chromatic.com/compare/vercel

**Comment by with-heart** [comment]
@alanpcurrie let's do this! I think there's a lot of value in setting up storybook for the project, especially with the thorough list of configs you've put forth.

What's needed for publishing to Chromatic?

**Comment by Dhaiwat10** [comment]
Excited to see how this turns out!

**Comment by alanpcurrie** [comment]
Hey folks, I've put a draft PR. Thought it was worth discussing the locale switching / Chakra issue that I ran into, to see if we can get it merged prior to a fix.  

Essentially - ee can have locale switching, or chakra styling with the current config, styling felt more important for now. worth a conversation though

I have also added typescript path aliases to match the Storybook path aliases - they make components imports nice and clean, again, worth a chat to see if other folks agree, if there is a preferred path alias format than @components/  maybe just components/ for example 

@with-heartchromatic Chromatic would be linked to the Developer-DAO github account and intructions to deploy are below

https://www.chromatic.com/docs/setup, 

happy to work with you, and the team to set it up

**Comment by narbs91** [comment]
@codingwithmanny @with-heart do we still want to keep this issue open?

**Comment by codingwithmanny** [comment]
@narbs91 
I would close it as it seem specific to the previous UI but good to know for the next version.

**Comment by alanpcurrie** [comment]
Hey folks, it's in no way coupled to the previous ui. It's the config that's valuable here. @with-heart I've pushed changes addressing your comments

**Comment by mhmulford0** [comment]
I'm closing this issue because it is stale and would require a great deal of work to be brought to the current base.

**Comment by alanpcurrie** [comment]
@mhmulford0 this PR would have been trivial to merge - not sure why it was closed?  https://github.com/Developer-DAO/developerdao.com/pull/241

**Comment by mhmulford0** [comment]
feel free to

**Comment by mhmulford0** [comment]
closed as we have migrated to monorepo
