### ISSUE TITLE
[Feature]: Web3 Wallet Connection/Token Search Functionality 

### ISSUE THREAD

**Issue by brandonfrulla** [Developer-DAO/developerdao.com#177]
### Context / Background / How This Idea Came To Fruition

Formally writing up my idea from the Discord here for the sake of traceability. Given that we are a Web3-based DAO, some baseline Web3 integrations should be a component of our site now while we build out additional use cases.

### Problem / Opportunity

Upon connection to the DeveloperDAO website, Web3 browser extensions like MM et. al. should be able to connect to our site.

### Proposed Solution / How It Can Be Improved

For now, acceptance criteria can be such that: 

- Following wallet connection, given that a wallet contains 1+ D_D token(s), the current homepage could then display their token first, as opposed to D_D token # 1, the current default functionality.

### Testing the changes

1. Open D_D site
2. Connect Web3 wallet
3. Observe that _your token_ is displayed in the search box, instead of Token # 1 (Mine is 3443, so functionality would show as follows in the screenshot)

<img width="1256" alt="Screen Shot 2021-11-10 at 12 25 06 PM" src="https://user-images.githubusercontent.com/51884427/141162460-f5438104-b01f-4c41-aa6b-87ca9b4eab3a.png">

**Comment by Dhaiwat10** [comment]
Thanks for creating this issue. FWIW, we already have a wallet integration for the mint functionality. You should have a look at that.

@Developer-DAO/site what are your opinions on having this feature added?

**Comment by brandonfrulla** [comment]
I minted directly through the contract, so I never actually saw the integration- sweet! That makes my life even easier

**Comment by brandonfrulla** [comment]
@Dhaiwat10 My original post in the discord has a good number of likes, so I think we can take that as support here. Do you want to assign it to me officially? Thanks in advance.

**Comment by narbs91** [comment]
I think it would be cool feature to have a global sign in on the site; however, do note that the current wallet implementation only resides on the `mint your token` page and doesn't carry over to the other pages at the moment.  So there will probably be some refactoring work to be done to shift the login to state to have it carry over to the pages

**Comment by brandonfrulla** [comment]
@codingwithmanny Hey there, that probably makes sense if there's about to be a major rework- do we have an ETA on the new site arrival?

**Comment by codingwithmanny** [comment]
Hoping that may be done this week. PR is https://github.com/Developer-DAO/developerdao.com/pull/159

**Comment by with-heart** [comment]
Since we're shifting ownership from developers to the design guild in order to focus the site around brand representation, we probably need to defer this conversation until we figure out what their plans are for the site. 

Personally I'm not sure we'll have a need for these types of integrations on the main site, similar to banklesshq.com being their public face with only marketing content. That doesn't mean we won't have use for it elsewhere in the DAO though, just that this probably won't end up being the project for it.

**Comment by narbs91** [comment]
As we are shifting the purpose of the website pending a decision from the design guild we are putting a pause on all non maintenance/house keeping issues.  As such i'll be closing this issue.  Thanks for the interest in the website but tune back a little later when the new direction has been established
