### ISSUE TITLE
Remove link to Opensea

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/developerdao.com#184]
### Context / Background / How This Idea Came To Fruition

From Nader's [message](https://discord.com/channels/883478451850473483/884852584941232169/909666569846669363)

![image](https://user-images.githubusercontent.com/39617427/141748625-c070e38e-e1d1-4197-bd89-d7ec2b30c5b4.png)

### Problem / Opportunity

> we are not trying to encourage people to buy the tokens on the secondary, at least until we launch the new Governance token.

### Proposed Solution / How It Can Be Improved

Remove the link to Opensea from the footer

### Testing the changes

-

**Comment by Dhaiwat10** [comment]
![image](https://user-images.githubusercontent.com/39617427/141749025-94c840c4-371d-4b9b-8f8c-a0746c282032.png)

**Comment by namanmanchanda09** [comment]
Hey @Dhaiwat10, please do assign this to me. Thank you!

**Comment by noahliechti** [comment]
Can we close this issue? We are actively encouraging people to buy from opensea:

<img width="708" alt="Screenshot 2022-02-26 at 17 58 46" src="https://user-images.githubusercontent.com/38284563/155851983-6253b07f-c2ef-4565-b013-a9a8ff06f510.png">

**Comment by Dhaiwat10** [comment]
@noahliechti good call, closing this
