### ISSUE TITLE
[Feature]: upgrade Next.js version to 12

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/developerdao.com#195]
### Context / Background / How This Idea Came To Fruition

We're still using Next.js v11. The latest version - v12 has [lots of serious benefits](https://nextjs.org/blog/next-12).

### Problem / Opportunity

^^

### Proposed Solution / How It Can Be Improved

Bump the `next` dependency to the latest verison

### Testing the changes

n/a

**Comment by Nazeeh21** [comment]
Closed by #232
