### ISSUE TITLE
![IMPORTANT NOTICE]! Development on the website is being put on pause

### ISSUE THREAD

**Issue by narbs91** [Developer-DAO/developerdao.com#196]
Hi there stranger, we at Developer DAO love your enthusiasm in wanting to get right into the thick of the action; however, with the recent changes introduced by the introduction of [Season 0](https://forum.developerdao.com/t/how-we-move-forward-as-a-dao-season-0/56) and the fact that we are now out of DEVS tokens for minting, the website in it's current form factor is out of date.  This is a real bummer for folks who've put in a lot of work to make the site what it is : ( (including your's truly).  Sometimes we have to learn how to let go and realize the new opportunities ahead of us.  This is a really exciting time for us as a DAO and there will be many more opportunities for us flex our design/coding/problem solving skills together.  

Since the website first launched its intent was to provide a means for any visitor to be able to mint a DEVS token to gain access to the community.  Many of the awesome features that have been added since then (and have kept coming up in the present) have centered around this same goal but it doesn't make sense anymore given the fact we are sold out of tokens.  Thus as maintainers of the site we are purposing on putting a pause on any further changes to the site until the Design Guild has decided what direction to take it.  There are a lot of great reusable pieces that we can look to continue to use but unfortunately much of the current functionality will need to be striped away as it no longer serves a purpose.

As of this moment any issue that is not deemed general maintenance or house keeping will be closed and marked with the `archived` label to signify that the this issue was a thing but not actually pursued.  Think of it as kind of a historical view of our brief time as a DAO.

Remember this doesn't mean the site is going away by any means but just that we have to take a bit more time to figure out the exact picture we want to paint with the beautiful canvas that is the website. 

- Narb

**Comment by ademidun** [comment]
For anyone curious, here is [the website redesign PR](https://github.com/Developer-DAO/developerdao.com/pull/159) that @narbs91  is referencing above.
