### ISSUE TITLE
[Feature]: alert about fake $CODE tokens

### ISSUE THREAD

**Issue by marcgarreau** [Developer-DAO/developerdao.com#199]
### Context / Background / How This Idea Came To Fruition

Scammers deployed a fake $CODE token ahead of our governance token launch.

### Problem / Opportunity

Unsuspecting web3 citizens in and outside of our community may fall prey to this scam and lose their hard-earned cryptobucks.

### Proposed Solution / How It Can Be Improved

Just some text to the homepage that warns people that our token hasn't launched yet and to beware fake/scam tokens. Official contract will be included on the website and on Twitter once its launched.

### Testing the changes

n/a

**Comment by oceans404** [comment]
Can I pick this up?

**Comment by Nazeeh21** [comment]
I am not sure, whether we still want this or not.
@with-heart your thoughts?

**Comment by marcgarreau** [comment]
I believe this concern has mostly come and gone, but we'll want to make sure the redesign includes links to the contracts (Genesis NFT and gov token, once launched). I'll close this ticket, but maintainers please reopen or create a new ticket as you feel appropriate. Thanks @oceans404 for volunteering at any rate!

**Comment by Nazeeh21** [comment]
> I believe this concern has mostly come and gone, but we'll want to make sure the redesign includes links to the contracts (Genesis NFT and gov token, once launched). I'll close this ticket, but maintainers please reopen or create a new ticket as you feel appropriate. Thanks @oceans404 for volunteering at any rate!

@with-heart Do we need this?
