### ISSUE TITLE
Implement Footer

### ISSUE THREAD

**Issue by Nazeeh21** [Developer-DAO/developerdao.com#206]

**Comment by leouonline** [comment]
I wanted to do this... but I needed to learn more about chakra. I would love to learn from your approach @andreivdev

**Comment by Nazeeh21** [comment]
@andreivdev  Assigned to you

**Comment by Nazeeh21** [comment]
@leouonline if you want, you both can collab on this.

**Comment by andreivdev** [comment]
@joneskj55 volunteered to work on this and I would really love to give other people the opportunity to contribute.

You guys let me know if you need any help. ❤️

**Comment by Nazeeh21** [comment]
Okay, so should I assign this to @joneskj55 and unassign you?

**Comment by joneskj55** [comment]
Hey @Nazeeh21, yes you can assign it to me. I should have at least a draft submitted later today. I'll reach out if I need any help. Thanks!
