### ISSUE TITLE
Implement Partners Section

### ISSUE THREAD

**Issue by Nazeeh21** [Developer-DAO/developerdao.com#209]

**Comment by myaowy** [comment]
I will take it and work on it.

**Comment by Nazeeh21** [comment]
Sure, sssigning you!

**Comment by Nazeeh21** [comment]
Hey @myaowy, just lmk if you are stuck somewhere or want my help on this, thanks

**Comment by andyrobert3** [comment]
Are you guys still working on this? 
if not happy to help out

**Comment by andyrobert3** [comment]
just joined the DAO and looking for projects to do here!

**Comment by myaowy** [comment]
oh no I'm so behind on this. @Nazeeh21, you can assign @andyrobert3 for this. I'm sorry I didn't implement that.

**Comment by Nazeeh21** [comment]
Np @myaowy, I'll assign @andyrobert3.
Over to you @andyrobert3

**Comment by Nazeeh21** [comment]
@andyrobert3 Can you create a draft PR or something like that when it's ready (no rush) so that we can have a look at the progress and help you out in possible ways?

**Comment by andyrobert3** [comment]
https://github.com/Developer-DAO/developerdao.com/pull/222

Waiting for the the partners icons section here

**Comment by andyrobert3** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/15076300/162997717-2b3181c1-d6cd-4567-aec9-8156518c6ea5.png">

**Comment by Nazeeh21** [comment]
Closed by #222
