### ISSUE TITLE
Favicon is not round and adjusted for different platforms

### ISSUE THREAD

**Issue by noahliechti** [Developer-DAO/developerdao.com#216]
### What happened?

This fix was already implemented in the pixel-avatars project and helps maintaining the continuous dao branding on different platforms.

Each platform comes with its own design (Android, Safari, Windows Tiles, ...) requirements. You can't just use the same picture everywhere. I use RealFaviconGenerator to craft the correct icons for every platform.

### How to reproduce the bug?

1. Go to developerdao.com
2. Look at favicon (it is a square)

<img width="456" alt="Screenshot_2022-02-27_at_15 40 55" src="https://user-images.githubusercontent.com/38284563/155899501-9458a7bf-bd1c-4bbb-891f-a55d48a78209.png">

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### What device type(s) did you see the problem on?

- [ ] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating system(s) did you see the problem on?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional information

Related to https://github.com/Developer-DAO/pixel-avatars/issues/111

**Comment by AurelienConte** [comment]
Hi ! 

I can take this PR if no one is working on it.

**Comment by AurelienConte** [comment]
I just submitted a new PR on the subject using the RealFaviconGenerator.
Let me know if it feet your need. On my side that fills the need.

You can test the project by running `yarn dev` and opening the `http://localhost:3000`

**Comment by noahliechti** [comment]
@AurelienConte there is already an existing PR #219
