### ISSUE TITLE
[Bug]: fix "temporarily closed" inaccuracy

### ISSUE THREAD

**Issue by marcgarreau** [Developer-DAO/developerdao.com#220]
### What happened?

I realize that the redesign is well under way, but seems prudent to update the verbiage in the joining section immediately:

```
How do I join?

Membership is temporarily closed but will be open again soon. Follow us on Twitter for updates!
```

I occasionally see questions about this in the Discord server and on Twitter.

### How to reproduce the bug?

(visit developerdao.com)

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### What device type(s) did you see the problem on?

- [ ] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating system(s) did you see the problem on?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional information

Options:
1. delete the section.
2. mention that membership is represented by an NFT, add link to opensea collection. 
3. mention the above + governance token coming Soon™.

I'm partial to 3.

**Comment by etr2460** [comment]
I fixed this in #221 so i think this can be closed
