### ISSUE TITLE
Update the links and social icons

### ISSUE THREAD

**Issue by Nazeeh21** [Developer-DAO/developerdao.com#226]
This is regarding the latest suggestions from kemp on discord
Ref link: https://discord.com/channels/883478451850473483/884852584941232169/971715630153756693
----------------
**Menu bar** 

think we should change "Latest Updates" to "Twitter"
Where are we sending "Events" - could be to the public Google calendar for DAO events in 📅-d_d-events , here is the link https://developerdao.notion.site/Calendar-43f22c4a37e747e399d7d265c554af67 
----------------
**Marquee**

Membership is currently open by purchasing the NFT so this needs to be updated
----------------

Remove Podcast
Remove Partners
Remove Learning Resources (it's super dead project)
Move newsletter to Discover
need to add YouTube to social buttons

Ref figma link: https://www.figma.com/file/W2MGe36aUKYzaE3EaWQIm5/Developer-DAO-website-2022?node-id=2%3A396

**Comment by kempsterrrr** [comment]
Thanks @Nazeeh21 - working on this now and will push an update to #224 🤝

**Comment by kempsterrrr** [comment]
All done. Updated #224 which hopefully should close this issue now

**Comment by Nazeeh21** [comment]
Thanks @kempsterrrr. The changes look amazing 👌🏻 . Closing this issue
