### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by Nazeeh21** [Developer-DAO/developerdao.com#227]
1- at the beginning of the website loading, images are not so fast at loading, so try loading that image faster

![image](https://user-images.githubusercontent.com/56908732/167388811-cd0667d4-096c-436e-acb3-7b5a3b7eb8e8.png)

2- align these icons horizontally center, so we can have equal amount of space between left and right text
![image](https://user-images.githubusercontent.com/56908732/167389211-b6e98445-6964-463e-8422-2376b7cc6bf9.png)

Do all these improvements for the Marquee at the bottom of the website as well.

**Comment by alanpcurrie** [comment]
Hey @Nazeeh21 I can pick this one up

**Comment by Nazeeh21** [comment]
Sure, all yours

**Comment by Nazeeh21** [comment]
Closed by #229
