### ISSUE TITLE
Add CMS

### ISSUE THREAD

**Issue by Nazeeh21** [Developer-DAO/developerdao.com#228]
We have decided to go with prismic, but we are open to suggestions, if anyone has a better alernative

**Comment by alanpcurrie** [comment]
Hey @Nazeeh21 I'd be happy to start on this. Is there an existing prismic account? or anything else I should know before progressing?

**Comment by Nazeeh21** [comment]
@alanpcurrie There is not an existing prismic account. I'll create one and share the credentials with you

**Comment by kempsterrrr** [comment]
in #244 there is the suggestion of using strapi as it;'s open-source FYI, have left a comment in response
