### ISSUE TITLE
[Chore]: Added Github actions to help with project maintenance 

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/developerdao.com#245]
### Context / Background / How This Idea Came To Fruition

Hello folks. Last week I asked in the server if people thought adding a bit of light automation to the repos on our Github org might help and generally, people were really supportive. See the poll [here](https://discord.com/channels/883478451850473483/915267870924095580/992406662575050823) - 95% I'm favour

### Problem / Opportunity

There are too many stale issues and PRs on our repo's that i think it would help to reduce. 

### Proposed Solution / How It Can Be Improved

What I'm suggesting is we implement this [GitHub action](https://github.com/actions/stale) that will automatically mark issues as stale once they have been inactive for X days and ideally notifies whoever was active on the issue/PR in the past to ask for an update. The hope is it might help with a) having a more up-to-date status of everything and b) more obvious for new contributors what is worth trying to help contribute to and what is not.

### Testing the changes

Need some help here testing is not my fortay 

### Additional Information

@myz1237 and I will created a PR test implementation

**Comment by mhmulford0** [comment]
@kempsterrrr just reviewing open issues. I see the branch was merged, are there any pending items for this?

**Comment by mhmulford0** [comment]
closing this as i believe it to be resolved.
