### ISSUE TITLE
Update Open Graph Image

### ISSUE THREAD

**Issue by mhmulford0** [Developer-DAO/developerdao.com#248]
The current image could use a bit of flare! This is what people will see when our link gets pasted into discord/twitter/etc so let's make it pop.

**Comment by kempsterrrr** [comment]
WIP meta image update, waiting on decision on new folks to include in this. When that's confirmed will update and share this for someone new to pick up ideally :)

![Image](https://user-images.githubusercontent.com/9025997/181392266-7fcf811e-ac79-4ca4-9734-75532e359b16.png)

**Comment by kempsterrrr** [comment]
any feedback welcome ofc

**Comment by kempsterrrr** [comment]
The final one I'm planning to use with update Explorer from #256 @mhmulford0 I've also fixed the overlap of the labels so someone can replace the image on the home page as well.

![Meta Image](https://user-images.githubusercontent.com/9025997/181467471-5bea3aa0-df06-4d1d-a4ec-6e05ae9d204f.png)
