### ISSUE TITLE
Update Design To Be More Diverse

### ISSUE THREAD

**Issue by mhmulford0** [Developer-DAO/developerdao.com#256]
As a group composed of many different sorts of people, our materials should reflect that. 

The design was released in its' current form as an effort to get a months-long initiative launched. As such, this important task was deferred. Now that we have caught up some, we must take the time to make this update. I am opening this to the community as I should not decide who represents us alone.

Please provide us with images of people that you feel reflect you or the DAO to be included in the image cluster on the design.

**Comment by tyronedunmore** [comment]
![matthew Henson](https://user-images.githubusercontent.com/59738073/181394188-4001c934-6793-429a-919e-2065c21d93fd.jpeg)
