### ISSUE TITLE
Reduce NFT data response time on E2E tests

### ISSUE THREAD

**Issue by fmoliveira** [Developer-DAO/developerdao.com#92]
## Problem

The library `use-nft` dispatches around 12 requests to load each token's data. On my connection (80Mbps with 11ms ping), each request takes anywhere from 200ms to 700ms and the total time to load NFT data is anything between 2s to 5s. It feels slow, especially because we're not fetching this directly from the blockchain, but from traditional Web2 APIs.

Despite being slow, I've had eventual timeouts when running E2E tests. Also, I've got rate-limited quite a few times in my local environment.

## Context

The [Ethers documentation: Provider API keys](https://docs.ethers.io/v5/api-keys/) says that by default, the library uses shared community API keys for Alchemy, Etherscan and Infura APIs. These keys are only recommended for low-traffic projects and early prototyping.

It also says that if we sign up to get our own API keys for all these services, we would get a much higher request rate and faster responses as well.

While I think we would still fall on the "low-traffic" use case, for now, it sounds interesting that getting our own API keys would improve the response time. And it'd also be relieving to have our request rate increased, reducing the chance of request errors.

## Proposal

~~Continue running local environments as it is, with the shared community keys, is the best setup in my opinion – no overhead added to develop locally.~~

~~For end-to-end testing and production – would it be a good idea to sign up for our own API keys in these services and experiment if the response times would be significantly faster as the Ethers documentation states?~~

See new proposal by @codingwithmanny below: https://github.com/Developer-DAO/developer-dao/issues/92#issuecomment-923863041

**Comment by codingwithmanny** [comment]
Might be worth having a script that keeps track of how many api requests are made.
The free tier for etherscan is about 100,000/day or 5/per second. Could get go over that limit every we run automated tests.

Just rethinking this it might make more sense to mock that whole thing really.

**Comment by fmoliveira** [comment]
@codingwithmanny I'm actually thinking of using the API keys only on tests run on CI.

- Local environment: uses shared community keys; you're free to put your personal keys on `.env` if you want, but it's not required for the app to work
- CI environment: has its own set of keys
- Production environment: also has its own set of keys, that can be different from CI to not share usage quota

I prefer having at least one smoke test running fully e2e to ensure we're dealing correctly with the NFT APIs. I'm favourable about mocking all the other e2e tests, though!

About API usage stats – does Etherscan provide something similar on its own dashboard? I know that Infura does, but I haven't used Etherscan API myself just yet.

**Comment by codingwithmanny** [comment]
@fmoliveira My worry because of the limits and the rate of contributions and ci tests run, it'll quickly fail more so that often.
I'm personally running the etherscan api right now for the last two days, and I've stayed within the limits and I still got failures.

**Comment by codingwithmanny** [comment]
@fmoliveira I was thinking about this again today and there has to be a way where we could just spin up hardhat (maybe even as a docker container) which would run a localhost 8545 and serve the contract locally. That way you don't need mainnet to get the data, all the functions work the same because everything is in the contract the same as on mainnet AND no API limits.

**Comment by with-heart** [comment]
> @fmoliveira I was thinking about this again today and there has to be a way where we could just spin up hardhat (maybe even as a docker container) which would run a localhost 8545 and serve the contract locally. That way you don't need mainnet to get the data, all the functions work the same because everything is in the contract the same as on mainnet AND no API limits.

I like this solution for the time being. Ideally, we should be able to sign up for Etherscan and various other API keys, but imo we need to mature as an org a little bit more first to have a process in place for managing various keys owned by the org.

**Comment by codingwithmanny** [comment]
That and adding Etherscan API keys in the CI tests will definitely break often. I've had to restart my script multiple times, have you I'm up to `46986` api requests now.

**Comment by with-heart** [comment]
Not nearly enough requests. WORK HARDER

**Comment by fmoliveira** [comment]
@codingwithmanny @with-heart This is an awesome idea! And great points about the API keys regarding limits and management.

I've edited the original post to discard my original proposal and included a link to your comment instead @codingwithmanny .

**Comment by codingwithmanny** [comment]
@fmoliveira I'm definitely curious myself. I didn't see a Docker image for this, but I imagine it should be crazy to build one either.

Definitely worth creating an issue for it, but if you'd like the tag team it, I'm down.

**Comment by gjsyme** [comment]
Not sure if I know exactly what you wanted, but I made a hardhat repo that can enumerate the Devs (to console right now but you could change that) or will serve as a minimal server for querying (defaults to 127.0.0.1:8545, but again, you could change that). I don't think this product necessarily should go in the web repo but here it is: https://github.com/gjsyme/hh-devs-for-revolution

**Comment by codingwithmanny** [comment]
WIP as a draft PR for the Docker implementation:
https://github.com/Developer-DAO/developer-dao-nft-contract/pull/1

**Comment by codingwithmanny** [comment]
@fmoliveira if I create the docker image (hosted on my DockerHub account for now), can you tag team this with me and create the cypress tests for it?

**Comment by gjsyme** [comment]
@codingwithmanny is this still on your radar and @fmoliveira did you see the question regarding cypress tests?

**Comment by codingwithmanny** [comment]
@gjsyme closing this out because most of this will go into #154
