### ISSUE TITLE
Missing Translation(s)

### ISSUE THREAD

**Issue by Nazeeh21** [Developer-DAO/developerdao.com#95]
### PR #

#94

### Translation Keys

projects

### List of missing locales

es, fr, ru, zh-CN, zh-HK, zh-TW, zh, pt, pt-BR, pt-PT

**Comment by codingwithmanny** [comment]
In relation to PR #94

**Comment by gjsyme** [comment]
Can close this issue as I have created the new tickets per the meeting 28Oct2021 (created #163 , #164 , #165 )

**Comment by codingwithmanny** [comment]
Let's close it out then and if more are needed, we just add more issues.
